-- GiaSu-KNTech schema (MVP).
-- This is designed to support:
-- Auth/User, Tutor approval, Availability, Booking, SePay payments,
-- Wallet holding/release, Withdraw, QuickMatch, Reports/Disputes, Admin.

CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(36) PRIMARY KEY,
  full_name VARCHAR(120) NOT NULL,
  username VARCHAR(100) NULL UNIQUE,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('STUDENT','TUTOR','ADMIN') NOT NULL DEFAULT 'STUDENT',
  phone VARCHAR(32) NULL,
  avatar_url TEXT NULL,
  status ENUM('ACTIVE','BANNED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tutor_profiles (
  user_id VARCHAR(36) PRIMARY KEY,
  bio TEXT NULL,
  school VARCHAR(190) NULL,
  major VARCHAR(190) NULL,
  year_of_study VARCHAR(32) NULL,
  hourly_rate DECIMAL(20,2) NULL,
  subjects_to_teach TEXT NOT NULL,
  is_verified ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  reject_reason TEXT NULL,
  card_gradient VARCHAR(190) NULL DEFAULT 'bg-gradient-to-r from-blue-600 via-indigo-600 to-[#13519c]',
  ekyc_status ENUM('NOT_RUN','AUTO_ACCEPTED','MANUAL_REVIEW') NOT NULL DEFAULT 'NOT_RUN',
  ekyc_score DECIMAL(5,2) NULL,
  ekyc_result JSON NULL,
  identity_submitted_at TIMESTAMP NULL,
  teaching_profile_completed_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (is_verified)
);

CREATE TABLE IF NOT EXISTS tutor_documents (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tutor_user_id VARCHAR(36) NOT NULL,
  doc_type ENUM('CCCD_FRONT','CCCD_BACK','PORTRAIT','CERTIFICATE','TRANSCRIPT','OTHER') NOT NULL DEFAULT 'OTHER',
  url TEXT NOT NULL,
  storage_key VARCHAR(255) NULL,
  original_name VARCHAR(255) NULL,
  mime_type VARCHAR(120) NULL,
  file_size_bytes INT NULL,
  status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (tutor_user_id),
  INDEX (status)
);

CREATE TABLE IF NOT EXISTS tutor_availability (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tutor_user_id VARCHAR(36) NOT NULL,
  weekday TINYINT NOT NULL, -- 0..6
  start_minute SMALLINT NOT NULL, -- minutes from 00:00
  end_minute SMALLINT NOT NULL,
  timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Ho_Chi_Minh',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (tutor_user_id),
  INDEX (weekday)
);

CREATE TABLE IF NOT EXISTS appointments (
  id VARCHAR(36) PRIMARY KEY,
  student_id VARCHAR(36) NOT NULL,
  tutor_id VARCHAR(36) NOT NULL,
  start_time DATETIME NOT NULL,
  end_time DATETIME NOT NULL,
  price_paid DECIMAL(20,2) NOT NULL,
  status ENUM('PENDING','CONFIRMED','CANCELLED','DONE') NOT NULL DEFAULT 'PENDING',
  payment_status ENUM('UNPAID','HOLDING','RELEASED','REFUNDED','FAILED') NOT NULL DEFAULT 'UNPAID',
  commission_percent_snapshot DECIMAL(5,2) NULL,
  commission_amount DECIMAL(20,2) NULL,
  tutor_earning DECIMAL(20,2) NULL,
  escrow_release_date DATETIME NULL,
  escrow_released_at DATETIME NULL,
  live_room_code VARCHAR(128) NULL,
  live_room_url TEXT NULL,
  student_completed_at DATETIME NULL,
  tutor_completed_at DATETIME NULL,
  completed_at DATETIME NULL,
  schedule_type ENUM('SINGLE','LONG_TERM') NOT NULL DEFAULT 'SINGLE',
  custom_schedule TEXT NULL,
  parent_appointment_id VARCHAR(36) NULL,
  session_number INT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (student_id),
  INDEX (tutor_id)
);

CREATE TABLE IF NOT EXISTS payments (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appointment_id VARCHAR(36) NOT NULL,
  amount DECIMAL(20,2) NOT NULL,
  status ENUM('PENDING','PAID','CANCELLED','FAILED') NOT NULL DEFAULT 'PENDING',
  provider ENUM('SEPAY') NOT NULL DEFAULT 'SEPAY',
  paid_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (appointment_id)
);

CREATE TABLE IF NOT EXISTS wallet_accounts (
  user_id VARCHAR(36) PRIMARY KEY,
  available_balance DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  holding_balance DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS wallet_ledger (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  entry_type ENUM(
    'TOPUP',
    'BOOKING_PAYMENT',
    'HOLD',
    'RELEASE',
    'REFUND',
    'WITHDRAW_REQUEST',
    'WITHDRAW_APPROVE',
    'WITHDRAW_REJECT'
  ) NOT NULL,
  amount DECIMAL(20,2) NOT NULL,
  ref_type VARCHAR(32) NULL,
  ref_id VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (user_id),
  INDEX (entry_type)
);

CREATE TABLE IF NOT EXISTS wallet_topups (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  amount DECIMAL(20,2) NOT NULL,
  status ENUM('PENDING','PAID','CANCELLED','FAILED') NOT NULL DEFAULT 'PENDING',
  provider ENUM('SEPAY') NOT NULL DEFAULT 'SEPAY',
  paid_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (user_id),
  INDEX (status)
);

CREATE TABLE IF NOT EXISTS withdraw_requests (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(36) NOT NULL,
  amount DECIMAL(20,2) NOT NULL,
  bank_code VARCHAR(32) NULL,
  bank_name VARCHAR(190) NULL,
  bank_account_no VARCHAR(64) NOT NULL,
  bank_account_name VARCHAR(120) NOT NULL,
  status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  admin_note TEXT NULL,
  receipt_url TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (user_id),
  INDEX (status)
);

CREATE TABLE IF NOT EXISTS quick_match_posts (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(36) NOT NULL,
  subject VARCHAR(120) NOT NULL,
  grade VARCHAR(32) NOT NULL,
  expected_rate DECIMAL(20,2) NULL,
  time_window_text VARCHAR(255) NULL,
  status ENUM('OPEN','CLOSED') NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (student_id),
  INDEX (status)
);

CREATE TABLE IF NOT EXISTS quick_match_applications (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  post_id BIGINT NOT NULL,
  tutor_id VARCHAR(36) NOT NULL,
  message VARCHAR(500) NULL,
  status ENUM('APPLIED','ACCEPTED','REJECTED') NOT NULL DEFAULT 'APPLIED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (post_id),
  INDEX (tutor_id),
  INDEX (status)
);

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appointment_id VARCHAR(36) NOT NULL,
  reporter_id VARCHAR(36) NOT NULL,
  target_id VARCHAR(36) NOT NULL,
  reason VARCHAR(120) NOT NULL,
  detail TEXT NULL,
  status ENUM('OPEN','RESOLVED') NOT NULL DEFAULT 'OPEN',
  resolution ENUM('REFUND','RELEASE','NONE') NOT NULL DEFAULT 'NONE',
  admin_note TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX (appointment_id),
  INDEX (status)
);

CREATE TABLE IF NOT EXISTS sepay_transactions (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  sepay_id INT NOT NULL UNIQUE,
  gateway VARCHAR(100) NOT NULL,
  transaction_date VARCHAR(32) NOT NULL,
  account_number VARCHAR(100) NULL,
  sub_account VARCHAR(250) NULL,
  amount_in DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  amount_out DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  accumulated DECIMAL(20,2) NOT NULL DEFAULT 0.00,
  code VARCHAR(250) NULL,
  transaction_content TEXT NULL,
  reference_code VARCHAR(255) NULL,
  body TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS system_logs (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(36) NULL,
  action VARCHAR(100) NOT NULL,
  details TEXT NULL,
  ip VARCHAR(45) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  recipient_id VARCHAR(36) NOT NULL,
  actor_id VARCHAR(36) NULL,
  type VARCHAR(60) NOT NULL,
  title VARCHAR(180) NOT NULL,
  body TEXT NOT NULL,
  link_url TEXT NULL,
  entity_type VARCHAR(60) NULL,
  entity_id VARCHAR(64) NULL,
  metadata JSON NULL,
  is_read TINYINT NOT NULL DEFAULT 0,
  read_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (recipient_id, is_read, created_at),
  INDEX (type),
  INDEX (entity_type, entity_id)
);

CREATE TABLE IF NOT EXISTS subjects (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS locations (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS grades (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS news (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  summary TEXT NULL,
  content TEXT NOT NULL,
  thumbnail_url TEXT NULL,
  category VARCHAR(50) NOT NULL DEFAULT 'Chung',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS documents (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  file_url TEXT NOT NULL,
  grade_tag VARCHAR(50) NOT NULL,
  type_tag VARCHAR(50) NOT NULL,
  subject_tag VARCHAR(50) NOT NULL,
  uploader_id VARCHAR(36) NOT NULL,
  uploader_name VARCHAR(120) NOT NULL,
  is_approved ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  reject_reason TEXT NULL,
  download_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  appointment_id VARCHAR(36) NULL,
  user_id VARCHAR(36) NOT NULL,
  message TEXT NOT NULL,
  file_url TEXT NULL,
  file_name VARCHAR(255) NULL,
  file_type VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (appointment_id),
  INDEX (created_at)
);

CREATE TABLE IF NOT EXISTS direct_messages (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  sender_id VARCHAR(36) NOT NULL,
  receiver_id VARCHAR(36) NOT NULL,
  message TEXT NOT NULL,
  is_read TINYINT NOT NULL DEFAULT 0,
  file_url TEXT NULL,
  file_name VARCHAR(255) NULL,
  file_type VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (sender_id),
  INDEX (receiver_id),
  INDEX (created_at)
);

CREATE TABLE IF NOT EXISTS tutor_reviews (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tutor_user_id VARCHAR(36) NOT NULL,
  student_name VARCHAR(120) NOT NULL,
  rating TINYINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (tutor_user_id),
  FOREIGN KEY (tutor_user_id) REFERENCES users(id) ON DELETE CASCADE
);
